-- create database customer;
use customer;

-- Q1. what is the total revenue generated by male vs female customers?
select gender as Gender, 
sum(purchase_amount_usd) as Total_revenue,
round(sum(purchase_amount_usd) * 100 / (select sum(purchase_amount_usd)from customer_data ), 2) as Percentage
from customer_data group by gender;

-- Q2. which customer used a discount but still spent more than avg purchase amount?
select customer_id as Customer_ID,
purchase_amount_usd as Amount_USD
from customer_data 
where discount_applied = "Yes" and purchase_amount_usd >= (select avg(purchase_amount_usd) from customer_data);

-- Q3. what are the top 5 products with the highest avg review ratings?
select item_purchased as Item, 
avg(review_rating) as AVG_Rating
from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. compare the avg purchase amount between standard and express delivery.
select shipping_type as "Delivery Type",
avg(purchase_amount_usd) 
from customer_data 
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. do subscribers spent more? compare avg spend and total revenue between subscribers and non- subscribers.
select subscription_status,
count(*) as Total_customers,
avg(purchase_amount_usd) as AVG_amount,
sum(purchase_amount_usd) as Total_revenue
from customer_data
group by subscription_status;

-- Q6. which 5 products have highest percentage of purchases with discount applied?
select item_purchased, 
round( sum(case when discount_applied = "Yes" then 1 else 0 end) * 100 /count(*) , 2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segment customers into new , returning and loyal based on their total number of previous purchases and 
-- show the count of each segment. 
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_segment;

-- Q8. what are the top 3 purchased products within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. are customers who are repeat buyers(more than 5 purchases) also likely to subscribers?
select subscription_status,
count(*) as Total_Customers,
round(100 * count(*) / (select count(*) from customer_data where previous_purchases > 5), 2) as Percentage
from customer_data
where previous_purchases > 5
group by subscription_status;

-- Q10. what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount_usd) as Total_revenue,
round( sum(purchase_amount_usd) * 100 / (select sum(purchase_amount_usd) from customer_data) ,2) as Percentage
from customer_data
group by age_group
order by Percentage desc;


